### ISSUE TITLE
Not success tested in Py3.3.4

### ISSUE THREAD

**Issue by hongjiujing** [bfishadow/SBB#3]
F:\git\SBB>SBB.py http://blog.sina.com.cn/u/1239657051
  File "F:\git\SBB\fengzongtangzhu\SBB.py", line 26
    print strUsage
                 ^
SyntaxError: invalid syntax

**Comment by bfishadow** [comment]
It's a known issue. Please read the document.

**Comment by hongjiujing** [comment]
can not get some tips from readme.md about this issue,you mean need to use  2.7.8 python?

**Comment by bfishadow** [comment]
Yes. Use the old style please. I'm not familiar with version 3. Sorry for that.
